version: "3.4"

services:

  selenium_hub_juinsa_shop:
    image: selenium/hub:3.141.59-zinc
    container_name: selenium_hub_juinsa_shop
    ports:
      - 4444:4444

  chrome_juinsa_shop:
    image: selenium/node-chrome:3.141.59-zinc
    container_name: chrome_juinsa_shop
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium_hub_juinsa_shop:selenium_hub_juinsa_shop
    environment:
      - HUB_HOST=selenium_hub_juinsa_shop
      - HUB_PORT=4444
      - SCREEN_WIDTH=2560
      - SCREEN_HEIGHT=1440
    ports:
      - 5555:5555

  juinsa_shop_web:
    build: ./ApachePhp
    container_name: juinsa_shop_web
    volumes:
    - ../:/var/www/html
    ports:
    - 80:80
    links:
      - juinsa_shop_db:db
      - chrome_juinsa_shop:chrome_juinsa_shop
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  juinsa_shop_db:
    build: ./MySql
    container_name: juinsa_shop_db
    ports:
      - 3306:3306
    volumes:
      - juinsa_shop_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}


volumes:
  juinsa_shop_db: